version: '3.5'


services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_PASSWORD: "superDevPassword"
      POSTGRES_USER: "user"
      POSTGRES_DB: "dev"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data