kafka_cart_request:
  request_topic: cart-request
  response_topic: cart-request-response
  brokers:
    - localhost:9092
    - localhost:9093
    - localhost:9094

kafka_inventory_request:
  request_topic: inventory-request
  response_topic: inventory-request-response
  brokers:
    - localhost:9092
    - localhost:9093
    - localhost:9094
