version: '3.5'

services:
  redis:
    image: "bitnami/redis:7.0.11"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=superDevPassword