kafka:
  request_topic: cart-request
  response_topic: cart-request-response
  brokers:
    - localhost:9092
    - localhost:9093
    - localhost:9094

postgres:
  username: user
  password: superDevPassword
  host: localhost:5432
  database: dev
